### ISSUE TITLE
UnboundLocalError: local variable 'dateToPrint' referenced before assignment

### ISSUE THREAD

**Issue by kklee998** [fat-duck/fatduck#2]
2018-10-10T16:45:29.241866+00:00 app[web.1]: [2018-10-10 16:45:29,241] ERROR in app: Exception on /631169214:AAHaES713JVqXSIy2Ys-eoSRr-dFOJGHGSQ [POST]
2018-10-10T16:45:29.241881+00:00 app[web.1]: Traceback (most recent call last):
2018-10-10T16:45:29.241884+00:00 app[web.1]: File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2018-10-10T16:45:29.241886+00:00 app[web.1]: response = self.full_dispatch_request()
2018-10-10T16:45:29.241888+00:00 app[web.1]: File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2018-10-10T16:45:29.241890+00:00 app[web.1]: rv = self.handle_user_exception(e)
2018-10-10T16:45:29.241891+00:00 app[web.1]: File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2018-10-10T16:45:29.241893+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2018-10-10T16:45:29.241894+00:00 app[web.1]: File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2018-10-10T16:45:29.241898+00:00 app[web.1]: raise value
2018-10-10T16:45:29.241899+00:00 app[web.1]: File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2018-10-10T16:45:29.241901+00:00 app[web.1]: rv = self.dispatch_request()
2018-10-10T16:45:29.241902+00:00 app[web.1]: File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2018-10-10T16:45:29.241904+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2018-10-10T16:45:29.241905+00:00 app[web.1]: File "/code/app.py", line 21, in process_update
2018-10-10T16:45:29.241907+00:00 app[web.1]: bot.process_update(update)
2018-10-10T16:45:29.241908+00:00 app[web.1]: File "/code/telegram_bot/bot.py", line 100, in process_update
2018-10-10T16:45:29.241909+00:00 app[web.1]: update), regex_tt.match(update["message"]["text"]).group().replace('/tt', '')))
2018-10-10T16:45:29.241911+00:00 app[web.1]: File "/code/reader/prettyCSV.py", line 74, in getDayTimetable
2018-10-10T16:45:29.241912+00:00 app[web.1]: return '<strong>Date:</strong> <em>' + dateToPrint + '</em>\n\n' + message
2018-10-10T16:45:29.241920+00:00 app[web.1]: UnboundLocalError: local variable 'dateToPrint' referenced before assignment

sometimes happen, dk why

**Comment by levin98** [comment]
Fixed
